### ISSUE TITLE
fishing mortality/harvest

### ISSUE THREAD

**Issue by lidach** [lidach/CampLabScallop#3]
- [x]  obtain information from Taylor/Dixie county 2018 (effort, catchability, state vessel counts 2016-2019) 

explore these options:

- [x]  Et*q

- [x]  constant U

- [x] q vary with effort or abundance

**Comment by perrydf** [comment]
<img width="756" alt="Screen Shot 2020-12-03 at 10 56 36 AM" src="https://user-images.githubusercontent.com/57648448/101054022-6ef5e380-3556-11eb-9ccd-8333bec5ab00.png">

**Comment by perrydf** [comment]
![image](https://user-images.githubusercontent.com/57648448/101054178-9cdb2800-3556-11eb-96b3-a2156bb5bf16.png)


Table from Page 1238

**Comment by jegranneman** [comment]
I uploaded a document called "FWRI Harvest Parameters" to the dropbox folder that contains estimates of u, q, and aerial surveys of vessels.

**Comment by Sborsum** [comment]
What is the functional form of this relationship? - type 2? Explore over a range of biomass.

coded in a q varying by Vulnerable biomass based on pine et al 2015 eq. 8.

Diana is working on Flags

**Comment by nickcfisch** [comment]
- [ ] Code in option for Constant q, Type II, and Type III functional responses with respect to Vulnerable Biomass

- [ ] Code in option to allow q to vary with effort

**Comment by nickcfisch** [comment]
For now maybe the simplest way to do above comment is to allow the explanatory variable in the functional response to be either vulnerable bio or effort. And later we can discuss with Ed and as a group whether we want to explore q as a function of effort, what shape we think it might be, and whether we want to allow q to vary as a function of both effort and abundance (i.e. maybe if abundance is really low but effort is high, search efficiency will still be good and catchability will be high (instead of low if q only varies as a function of abundance in a type-III type response)).

**Comment by zsiders** [comment]
I took a look at the Pine et al. (2015) paper. The original equation is q_t = q_max / (1+k_q*B_t); where q_t is the catchability at time, q_max is the maximum catchability at low stock size, k_q is a scaling constant (e.g. 2/B_0); and B_t is the biomass. If you generate q_t over a range of B_t, you end up with a declining exponential function as a function of B_t. This is from Hilborn & Walters (1992). 
[q_t_original.pdf](https://github.com/lidach/CampLabScallop/files/5696975/q_t_original.pdf)

My tentative answer to do the "type III" form is to just put an exponential on B_t in the above equation; less than 1 = slower q decline, greater than 1 is faster q decline. You also need to exponentiate the B_t in the calculation of Catch; C=qEB^X.
